server:
  port: 8004 #微服务端口

spring:
  application:
    name: service-cms #服务名
  profiles:
    active: dev #环境设置 dev表示构建阶段，test表示测试阶段，prod表示发布阶段
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulischool?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson: #我们的时区是东八区，应该加8个小时，时区显示格式也需要改成我们想要的
    date-format: yyyy-MM-DD HH:mm:ss
    time-zone: GMT+8 #GMT%2B8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos
  redis: #redis配置
    host: 127.0.0.1 #你的redis地址
    port: 6379 #端口号
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath:com/yzpnb/cmsservice/mapper/xml/*.xml #配置mapper xml文件的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志