server:
  port: 8005 #微服务端口

spring:
  application:
    name: service-msm #服务名
  profiles:
    active: dev #环境设置 dev表示构建阶段，test表示测试阶段，prod表示发布阶段
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos
  redis: #redis配置
    host: 127.0.0.1 #你的redis地址
    port: 6379 #端口号
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0